# This CI configuration expects a remote XCode server.
#

# Note: disabled the normal building while working on 
# releasecandidate support by adding 
#  only:
#     - when_release_candidate_support_is_complete
# sections

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: normal

# the standard debug build, will produce adhoc and enterprise 
# this build will run on push to any branch
#
build_project_debug:
  stage: build
  script:
    - .build-release/ci_build_wrapper.sh Debug 2>&1 | tee build.log
  tags:
    - iOS_10
    - xcode_8-3
    - osx_10-12-4
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: always
    expire_in: 8 weeks
    paths:
      - ./*.log
      - dsyms.zip
  allow_failure: false


# the standard release build, will produce adhoc and enterprise 
# this build will run on push to any branch
#
build_project_release:
  stage: build
  script:
    - .build-release/ci_build_wrapper.sh Release 2>&1 | tee build.log
  tags:
    - iOS_10
    - xcode_8-3
    - osx_10-12-4
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: always
    expire_in: 8 weeks
    paths:
      - ./*.log
      - dsyms.zip
  allow_failure: false


# a debug build configured to run on engineering devnet it produces adhoc and enterprise outputs
# this build will run on push to branch develop or experimental/ci-runner-devnet
#
build_project_debug_devnet:
  stage: build
  script:
    - .build-release/ci_build_wrapper.sh Debug devnet 2>&1 | tee build.log
  tags:
    - iOS_10
    - xcode_8-3
    - osx_10-12-4
  only:
    - develop
    - experimental/ci-runner-devnet
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: always
    expire_in: 8 weeks
    paths:
      - ./*.log
      - dsyms.zip
  allow_failure: false


# A release build with store ipa suitable for uploading to Apple.
# The release engineer controls the version number (BundleVersion) via a file local 
# to the build machine so keep them advised.
#
build_project_releasecandidate:
  stage: build
  script:
    - .build-release/ci_build_wrapper.sh Release releasecandidate 2>&1 | tee build.log
  tags:
    - iOS_10
    - xcode_8-3
    - osx_10-12-4
  only:
    - release/candidate
    - release/beta
    - experimental/ci-releasecandidate
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: always
    expire_in: 8 weeks
    paths:
      - ./*.log
      - dsyms.zip
  allow_failure: false
